### PR TITLE
Fix example compilation and use travis

### PR DESCRIPTION
**Pull request by arporter**
For #20.

### CODE REVIEW

**Comment by arporter** [comment]
This is a small fix to ensure that the example compiles. It also brings in the use of Travis to check that both the serial and parallel versions of the example (and therefore the library) build and run.
Ready for review from either @rupertford or @hiker.

**Comment by hiker** [comment]
Looks mostly good, I've merged in latest master, and compilation still works (including opencl library). The only thing missing is a reference in the top level README.md to the compiler_setup directory (where F90, F90FLAGS etc are specified).

**Comment by arporter** [comment]
Thanks @hiker. I've updated the README so it's ready for review again.

**Review by hiker — APPROVED** [review]
Is all looking good, thanks a lot!

**Pull request merged**
